repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v5.0.0
    hooks:
      - id: trailing-whitespace
        args: [--markdown-linebreak-ext=md]
      - id: end-of-file-fixer
      - id: check-yaml
      - id: check-toml
      - id: check-merge-conflict
      - id: mixed-line-ending
        args: [--fix=lf]
      - id: check-added-large-files
        args: [--maxkb=500]

  - repo: https://github.com/igorshubovych/markdownlint-cli
    rev: v0.45.0
    hooks:
      - id: markdownlint
        args: [--config, .markdownlint.yaml]

  - repo: local
    hooks:
      - id: prettier
        name: prettier
        entry: bun run prettier --write --ignore-unknown
        language: system
        files: \.(astro|css|html|js|json|jsx|md|mjs|ts|tsx|yaml|yml)$
